### ISSUE TITLE
Routing bug on single article menu links

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#216]
Cannot access an article by url on the front end when it is not under a category

Example: creating an "about us" page - want the URL to be /about-us but just get a 404. Tried adding a single article menu link but this doesn't find the article either!

**Comment by Smith0r** [comment]
Agh, that's an annoying one! Added to bug fix release!

**Comment by rbertram90** [comment]
Additionally you can put the article under the site-pages category but the alias will not work until the category itself is in a menu.

**Comment by Smith0r** [comment]
Curiously I couldn't replicate this bug. Here's my steps and findings:

I created a new category, and a new article. I then tested the normal router links SITE_URL/content/article/category-alias/article-alias and SITE_URL/content/category/category-alias - both of these worked.

I then created a new menu item to point to the new article, SITE_URL/article-alias, which worked.
I deleted the new article menu item, and created a new category menu item, and attempted to view the article at SITE_URL/category-alias/article-alias which worked.

The only time I got "Article not found" was when the article did not have a category which is expected behaviour due to settings that are found in the category that apply to the articles within it.

In the commit above i've ensured that all articles now are required to be set in a category, the form will not submit without one being chosen!

Can you verify for me that your components/content/router.php is the same as [this one](https://github.com/timbercms/timbercms/blob/2.0.1/components/content/router.php)?
